name: Update Minified Files

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "questionnaire.js"
      - "questionnaire.css"

jobs:
  minify:
    runs-on: ubuntu-latest
    # Skip if automated commit
    if: ${{ !contains(github.event.head_commit.message, 'Update minified files') }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Minify JavaScript and CSS
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: .
          output: .
          js_file: "questionnaire.js"
          css_file: "questionnaire.css"
          js_min_file: "questionnaire.min.js"
          css_min_file: "questionnaire.min.css"

      - name: Commit and push minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update minified files"
          file_pattern: "*.min.js *.min.css"
